### ISSUE TITLE
Switch from netlify to cloudflare for deployment

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow-app#11]
Why? What we use by default and can have a private repo.

One issue: the form (but not a big deal - could lose it for now!)

## Acceptance

- [ ] Flowershow.app served by cloudflare pages **✅2023-10-19** 
- [ ] Signup form still working (or removed?) ⏭️
- [ ] Exported / backed up signup list from netlify
- [ ] Netlify build archived

## Tasks

- [x] Setup deployment on cloudflare pages (including copying over env variables) **✅2023-10-19 https://flowershow-app.pages.dev/**
- [ ] Decide whether to keep form ...
- [ ] If keep form: use functions or similar to store form submissions

**Comment by rufuspollock** [comment]
@olayway flagging this item.

wdyt about keeping the form or not?
